seed: 42

save_dir: ./experiments/
save_name: synthetic_train

resume: False
load_path: ~
load_name: ~
overwrite: False
pretrain: ~

epoch: 1
iter: 400000
batch_size: 128
eval_batch_size: 128
num_eval_iter: 1000

model:
  name: TTR
  letter_size: 43
  img_size: [32, 128]
  patch_size: [4, 4]
  embed_dim: 512
  num_heads: 8
  position_attention_hidden: 64
  mask_ratio: 0

dataset:
  train:
    name: SyntheticTurkishStyleText
    root: ./data/STS-TR
    letters: 0123456789abcçdefgğhıijklmnoöpqrsştuüvwxyz
    maxLength: 25

  val:
    name: TurkishSceneTextDataset
    root: ./data/TS-TR/TEST
    letters: 0123456789abcçdefgğhıijklmnoöpqrsştuüvwxyz
    maxLength: 25

optimizer:
  name: AdamW
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0

clip_grad: 20

scheduler:
  name: onecyclelr

loss:
  name: CrossEntropyLoss
  label_smoothing: 0

gpu: 0
num_workers: 4
